version: '3'

services:
  fusion-elasticsearch:
    container_name: fusion-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    #restart: on-failure
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - cluster.name=fusion-docker-es-cluster
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - fusionlognet

  fusion-kibana:
    container_name: fusion-kibana
    image: docker.elastic.co/kibana/kibana:7.6.1
    #restart: on-failure
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: fusion-kibana
      ELASTICSEARCH_HOSTS: http://fusion-elasticsearch:9200
    networks:
      - fusionlognet

networks:
  fusionlognet:
